### ISSUE TITLE
waiting for implementation

### ISSUE THREAD

**Issue by gmyofustc** [SaeedNajafi/pytorch-ocd#1]
Hi, I also read the OCD Paper, the authors say they will release the code, hope this information can be shared

**Comment by SaeedNajafi** [comment]
Hi, I was waiting for the main authors to release their code.
It seems we should re-implement it.
I will squeeze it into my schedule during this week.

**Comment by Entonytang** [comment]
Can this code re-implement the experiments in WSJ？ how to set the parameters tua?

**Comment by SaeedNajafi** [comment]
No, this code is not for fully replicating the paper's experiments.
While constructing the OCD object, you can pass in `tua`. The paper seems to be using `tua` close to zero.
https://github.com/SaeedNajafi/pytorch-ocd/blob/master/ocd/__init__.py#L38
